### ISSUE TITLE
Disparity Estimation

### ISSUE THREAD

**Issue by jingnanopt** [PlenopticToolbox/PlenopticToolbox2.0#2]
FileNotFoundError: [Errno 2] No such file or directory: '/home/jing/Downloads/PlenopticToolbox2.0-master/THUMBNAILS/Plant_small.xml'

**Comment by PlenopticToolbox** [comment]
Hello! Sorry, I didn't see it before. 
The error indicates that you don't have the correct files in the right place.
The THUMBNAILS folder contains a down-scaled version of the images, therefore not suitable for real applications. You should download the real images from [here](https://drive.google.com/open?id=17I6nTf4GLYiO9fdWITEy155F-OaonaeQ) as explained in the main page. 
Once you have the real image (let's say you are using Plant image) you should have also a configuration file (in this case is called _Configuration_R29_tbg.xml_ in the same folder). If you give as input to the disparity sample script the correct path, then it will work.
Sorry, it may be that this was not fully explained. I will try to add more detailed explanation at the main page.
