### ISSUE TITLE
read_image.py  Error

### ISSUE THREAD

**Issue by huohuohuohuohuohuohuohuo** [PlenopticToolbox/PlenopticToolbox2.0#3]
When I run the read_image.py(I have rename the .xml to Camera_Processed.xml and I have the Camera_Processed.png) ,it gives me a error like this:
lenses, scene_type = imgIO.load_scene(path) missing 1 required positional argument:'calc_err'.

And I look for the imgIO.py ,it says;
def load_scene(filename, calc_err):

So how can I fix this error ?
Thank you so much.

And I change the statement to lenses, scene_type = imgIO.load_scene(path,1).(I have the Camera_Processed_disp.png)
I get this:
$ python3 read_image.py Camera_Processed.xml
Traceback (most recent call last):
  File "read_image.py", line 9, in <module>
    lenses, scene_type = imgIO.load_scene(path,1)
  File "/home/jdy/Huoxiao/toolbox2.0/PlenopticToolbox2.0-master/python/samples/plenopticIO/imgIO.py", line 161, in load_scene
    lenses = load_with_disp(img_filename, disp_name, filename)
  File "/home/jdy/Huoxiao/toolbox2.0/PlenopticToolbox2.0-master/python/samples/plenopticIO/imgIO.py", line 207, in load_with_disp
    disp_interp = sinterp.RectBivariateSpline(gridy, gridx, disp_data)
  File "/home/jdy/.pyenv/versions/3.7.0/lib/python3.7/site-packages/scipy/interpolate/fitpack2.py", line 1168, in __init__
    raise ValueError('x dimension of z must have same number of '
ValueError: x dimension of z must have same number of elements as x

Then I change the statement to lenses, scene_type = imgIO.load_scene(path,0).
I get this:
$ python3 read_image.py Camera_Processed.xml
Basis: [[ 8.66025360e-01 -8.74227766e-08]
 [ 5.00000089e-01  1.00000000e+00]] switch False
Traceback (most recent call last):
  File "read_image.py", line 9, in <module>
    lenses, scene_type = imgIO.load_scene(path,0)
ValueError: too many values to unpack (expected 2)

How can I fix this ?
Thank you so much.

**Comment by PlenopticToolbox** [comment]
Hello,
Please, if I do not answer here and you need something, reach me via e-mail at: lpa@informatik.uni-kiel.de.
Somehow github is not giving me any notification of new issues, so it takes time for me to see it.

Basically I forgot to add calc_err = False by default on the scene loading method (calc_err is used if you use synthetic images and you need to read also the ground truth/baseline image).

Please try again (with the 2 changes to imgIO.py and read_image.py that I just did) and it should work.

Luca
